include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: false
    - prefer_single_quotes: true
    - sort_constructors_first: true
    - sort_unnamed_constructors_first: true
    - prefer_final_locals: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - unnecessary_await_in_return: true
    - prefer_relative_imports: true
